
name: Deploy to Amazon ECS

on:
  workflow_call:


permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_DEPLOY_ROLE_ARN }}
          role-session-name: github-actions-app-ecs-deploy

      - name: Render frontend task definition
        id: render-frontend-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: .aws/pet-clinic-frontend.json
          container-name: petclinic-frontend
          image: 261371110333.dkr.ecr.us-east-1.amazonaws.com/petclinic-frontend:latest

      - name: Deploy frontend service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.render-frontend-task-def.outputs.task-definition }}
          service: tf-ecs-petclinic-frontend
          cluster: tf-ecs-cluster

      - name: Render backend task definition
        id: render-backend-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: .aws/pet-clinic-backend.json
          container-name: petclinic-backend
          image: 261371110333.dkr.ecr.us-east-1.amazonaws.com/petclinic-backend:latest

      - name: Deploy backend service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.render-backend-task-def.outputs.task-definition }}
          service: tf-ecs-petclinic-backend
          cluster: tf-ecs-cluster

