name: Github actions - AWS CICD

on:
  # push:
    # branches: [main]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml

  deploy:
    needs: terraform
    uses: ./.github/workflows/aws-ecs-deploy.yml