name: Terraform Infrastructure CICD

on:
  workflow_call:
  push:
    branches: [main]
    paths:
      - '**.tf'
      - '**.tfvars'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
            aws-region: ${{ vars.AWS_REGION }}
            role-to-assume: ${{ vars.AWS_TERRAFORM_ROLE_ARN }}
            role-session-name: github-actions-tf-infra
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.7.6

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Initialize
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -input=false

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false